<?php

namespace Database\Seeders;

use App\Models\Worlds\Biome;
use Illuminate\Database\Seeder;

class BiomeSeeder extends Seeder
{
    public function run()
    {
        $biomes = array(
            array(
                'name' => 'Rock Bottom',
                'slug' => 'rock_bottom',
                'description' => '',
                'alt_description' => '',
                'height' => 10,
                'passable' => true,
                'energy_cost' => 10,
                'liquid' => true,
                'solid' => false,
                'gas' => false,
                'plasma' => false,
                'red' => 40,
                'green' => 100,
                'blue' => 138,
            ),
            array(
                'name' => 'Deep Water',
                'slug' => 'deep_water',
                'description' => '',
                'alt_description' => '',
                'height' => 20,
                'passable' => true,
                'energy_cost' => 10,
                'liquid' => true,
                'solid' => false,
                'gas' => false,
                'plasma' => false,
                'red' => 48,
                'green' => 113,
                'blue' => 155,
            ),
            array(
                'name' => 'Shallow Water',
                'slug' => 'shallow_water',
                'description' => '',
                'alt_description' => '',
                'height' => 30,
                'passable' => true,
                'energy_cost' => 10,
                'liquid' => true,
                'solid' => false,
                'gas' => false,
                'plasma' => false,
                'red' => 39,
                'green' => 125,
                'blue' => 180,
            ),
            array(
                'name' => 'Water',
                'slug' => 'water',
                'description' => '',
                'alt_description' => '',
                'height' => 45,
                'passable' => true,
                'energy_cost' => 10,
                'liquid' => true,
                'solid' => false,
                'gas' => false,
                'plasma' => false,
                'red' => 31,
                'green' => 136,
                'blue' => 204,
            ),
            array(
                'name' => 'Wet Sand',
                'slug' => 'wet_sand',
                'description' => '',
                'alt_description' => '',
                'height' => 50,
                'passable' => true,
                'energy_cost' => 20,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 118,
                'green' => 167,
                'blue' => 140,
            ),
            array(
                'name' => 'Sand',
                'slug' => 'sand',
                'description' => '',
                'alt_description' => '',
                'height' => 53,
                'passable' => true,
                'energy_cost' => 15,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 205,
                'green' => 198,
                'blue' => 76,
            ),
            array(
                'name' => 'Dirt',
                'slug' => 'dirt',
                'description' => '',
                'alt_description' => '',
                'height' => 56,
                'passable' => true,
                'energy_cost' => 20,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 192,
                'green' => 171,
                'blue' => 69,
            ),
            array(
                'name' => 'Soil',
                'slug' => 'soil',
                'description' => '',
                'alt_description' => '',
                'height' => 58,
                'passable' => true,
                'energy_cost' => 10,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 155,
                'green' => 90,
                'blue' => 48,
            ),
            array(
                'name' => 'Grass',
                'slug' => 'grass',
                'description' => '',
                'alt_description' => '',
                'height' => 60,
                'passable' => true,
                'energy_cost' => 10,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 115,
                'green' => 123,
                'blue' => 48,
            ),
            array(
                'name' => 'Bush',
                'slug' => 'bush',
                'description' => '',
                'alt_description' => '',
                'height' => 65,
                'passable' => true,
                'energy_cost' => 11,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 71,
                'green' => 140,
                'blue' => 59,
            ),
            array(
                'name' => 'Forest',
                'slug' => 'forest',
                'description' => '',
                'alt_description' => '',
                'height' => 70,
                'passable' => true,
                'energy_cost' => 15,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 67,
                'green' => 124,
                'blue' => 70,
            ),
            array(
                'name' => 'Stone',
                'slug' => 'stone',
                'description' => '',
                'alt_description' => '',
                'height' => 75,
                'passable' => true,
                'energy_cost' => 12,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 72,
                'green' => 113,
                'blue' => 79,
            ),
            array(
                'name' => 'Hill',
                'slug' => 'hill',
                'description' => '',
                'alt_description' => '',
                'height' => 80,
                'passable' => true,
                'energy_cost' => 15,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 115,
                'green' => 150,
                'blue' => 128,
            ),
            array(
                'name' => 'Rock',
                'slug' => 'rock',
                'description' => '',
                'alt_description' => '',
                'height' => 90,
                'passable' => true,
                'energy_cost' => 30,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 161,
                'green' => 175,
                'blue' => 184,
            ),
            array(
                'name' => 'Snow',
                'slug' => 'snow',
                'description' => '',
                'alt_description' => '',
                'height' => 100,
                'passable' => true,
                'energy_cost' => 40,
                'liquid' => false,
                'solid' => true,
                'gas' => false,
                'plasma' => false,
                'red' => 204,
                'green' => 222,
                'blue' => 234,
            ),
        );
        foreach ($biomes as $biome) {
            Biome::create($biome);
        }
    }
}
